version: "3"

services:

  node0:
    build: .
    image: bitp2p
    ports:
        - "10003:10000"

  node1:
    image: bitp2p
    ports:
        - "10001:10000"

  node2:
    image: bitp2p
    ports:
        - "10002:10000"
